#!/bin/sh
set -eu

keys="/org/gnome/desktop/interface/cursor-theme /org/gnome/desktop/interface/icon-theme /org/gnome/desktop/interface/gtk-theme"
keys="$keys /org/gnome/desktop/sound/theme-name /org/gnome/desktop/sound/input-feedback-sounds"
keys="$keys /org/gnome/mutter/center-new-windows"

for k in $keys; do
    dconf reset $k
done

